import { format } from 'date-fns'

const today = format(new Date(), 'yyyy-MM-dd')
const tomorrow = format(new Date(Date.now() + 86400000), 'yyyy-MM-dd')
const nextWeek = format(new Date(Date.now() + 7 * 86400000), 'yyyy-MM-dd')

export const defaultData = {
    tasks: [
        {
            id: 'task-1',
            title: 'Set up weekly review system',
            status: 'In Progress',
            tags: ['productivity', 'systems'],
            dueDate: today,
            completed: false,
            priority: 'High',
            projectId: 'project-1',
            notes: '',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'task-2',
            title: 'Read Atomic Habits chapter 3',
            status: 'Not Started',
            tags: ['reading', 'learning'],
            dueDate: tomorrow,
            completed: false,
            priority: 'Medium',
            projectId: null,
            notes: '',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'task-3',
            title: 'Write morning pages',
            status: 'Done',
            tags: ['journaling', 'mindfulness'],
            dueDate: today,
            completed: true,
            priority: 'Low',
            projectId: null,
            notes: '',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'task-4',
            title: 'Plan Q1 goals',
            status: 'Not Started',
            tags: ['planning', 'goals'],
            dueDate: nextWeek,
            completed: false,
            priority: 'High',
            projectId: 'project-2',
            notes: '',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'task-5',
            title: 'Organize digital files',
            status: 'In Progress',
            tags: ['organization'],
            dueDate: nextWeek,
            completed: false,
            priority: 'Medium',
            projectId: null,
            notes: '',
            createdAt: new Date().toISOString(),
        },
    ],
    projects: [
        {
            id: 'project-1',
            title: 'Personal Knowledge System',
            status: 'Active',
            tags: ['productivity', 'learning'],
            dueDate: nextWeek,
            progress: 35,
            areaId: 'area-1',
            description: 'Build a comprehensive personal knowledge management system',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'project-2',
            title: 'Health & Fitness Overhaul',
            status: 'Active',
            tags: ['health', 'fitness'],
            dueDate: nextWeek,
            progress: 60,
            areaId: 'area-2',
            description: 'Complete fitness and nutrition transformation',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'project-3',
            title: 'Learn TypeScript',
            status: 'On Hold',
            tags: ['coding', 'learning'],
            dueDate: nextWeek,
            progress: 20,
            areaId: 'area-3',
            description: 'Master TypeScript for professional development',
            createdAt: new Date().toISOString(),
        },
    ],
    goals: [
        {
            id: 'goal-1',
            title: 'Read 24 books this year',
            status: 'Active',
            tags: ['learning', 'reading'],
            dueDate: '2025-12-31',
            progress: 42,
            areaId: 'area-1',
            metric: '10/24 books',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'goal-2',
            title: 'Exercise 4x per week',
            status: 'Active',
            tags: ['health', 'fitness'],
            dueDate: '2025-12-31',
            progress: 75,
            areaId: 'area-2',
            metric: '3/4 days this week',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'goal-3',
            title: 'Save $10,000 emergency fund',
            status: 'Active',
            tags: ['finance'],
            dueDate: '2025-12-31',
            progress: 55,
            areaId: 'area-4',
            metric: '$5,500 / $10,000',
            createdAt: new Date().toISOString(),
        },
    ],
    notes: [
        {
            id: 'note-1',
            title: 'The Power of Habit - Key Insights',
            tags: ['reading', 'psychology'],
            areaId: 'area-1',
            content: [
                { id: 'b1', type: 'heading1', content: 'The Power of Habit - Key Insights' },
                { id: 'b2', type: 'callout', content: '💡 Habits are formed through a loop: Cue → Routine → Reward' },
                { id: 'b3', type: 'heading2', content: 'Core Concepts' },
                { id: 'b4', type: 'bullet', content: 'The habit loop: every habit has a cue, routine, and reward' },
                { id: 'b5', type: 'bullet', content: 'Keystone habits create ripple effects in other areas of life' },
                { id: 'b6', type: 'bullet', content: 'Belief is essential for habit change' },
                { id: 'b7', type: 'divider', content: '' },
                { id: 'b8', type: 'heading2', content: 'My Takeaways' },
                { id: 'b9', type: 'paragraph', content: 'Focus on identifying my keystone habits first. Exercise seems to be mine.' },
            ],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 'note-2',
            title: 'Weekly Review Template',
            tags: ['productivity', 'templates'],
            areaId: 'area-1',
            content: [
                { id: 'b1', type: 'heading1', content: 'Weekly Review Template' },
                { id: 'b2', type: 'heading2', content: 'What went well?' },
                { id: 'b3', type: 'bullet', content: 'List your wins here' },
                { id: 'b4', type: 'heading2', content: 'What could be improved?' },
                { id: 'b5', type: 'bullet', content: 'Areas for growth' },
                { id: 'b6', type: 'heading2', content: 'Next week priorities' },
                { id: 'b7', type: 'bullet', content: 'Top 3 priorities' },
            ],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ],
    areas: [
        { id: 'area-1', title: 'Learning & Growth', icon: '📚', description: 'Books, courses, skills', color: '#2eaadc' },
        { id: 'area-2', title: 'Health & Fitness', icon: '💪', description: 'Exercise, nutrition, sleep', color: '#0f7b6c' },
        { id: 'area-3', title: 'Career & Work', icon: '💼', description: 'Professional development', color: '#6940a5' },
        { id: 'area-4', title: 'Finance', icon: '💰', description: 'Savings, investments, budget', color: '#d9730d' },
        { id: 'area-5', title: 'Relationships', icon: '❤️', description: 'Family, friends, community', color: '#e03e3e' },
        { id: 'area-6', title: 'Creativity', icon: '🎨', description: 'Art, writing, music', color: '#0b6e99' },
    ],
    resources: [
        {
            id: 'resource-1',
            title: 'Atomic Habits',
            type: 'Book',
            url: '',
            tags: ['habits', 'productivity'],
            status: 'Reading',
            areaId: 'area-1',
            notes: 'By James Clear. Essential reading for habit formation.',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'resource-2',
            title: 'Building a Second Brain',
            type: 'Book',
            url: '',
            tags: ['pkm', 'productivity'],
            status: 'To Read',
            areaId: 'area-1',
            notes: 'By Tiago Forte. About personal knowledge management.',
            createdAt: new Date().toISOString(),
        },
        {
            id: 'resource-3',
            title: 'Notion Second Brain Template',
            type: 'Website',
            url: 'https://notion.so',
            tags: ['tools', 'productivity'],
            status: 'Active',
            areaId: 'area-1',
            notes: 'Inspiration for this app.',
            createdAt: new Date().toISOString(),
        },
    ],
    journal: [
        {
            id: 'journal-1',
            title: `Journal - ${format(new Date(), 'MMMM d, yyyy')}`,
            date: today,
            mood: 'Good',
            content: [
                { id: 'b1', type: 'heading2', content: 'Morning Reflection' },
                { id: 'b2', type: 'paragraph', content: 'Today I want to focus on deep work and making progress on my PKM system.' },
                { id: 'b3', type: 'heading2', content: 'Gratitude' },
                { id: 'b4', type: 'bullet', content: 'Grateful for a productive morning' },
                { id: 'b5', type: 'bullet', content: 'Grateful for good health' },
                { id: 'b6', type: 'heading2', content: 'Intentions for today' },
                { id: 'b7', type: 'bullet', content: 'Complete the weekly review' },
                { id: 'b8', type: 'bullet', content: 'Read for 30 minutes' },
            ],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ],
    archive: [],
}
